export enum MensajeType {
	REQUERIDO = "campo requerido",
	EMAIL_INVALIDO = "email invalido",
	MIN_SEIS = "min seis caracteres",
	CONTRASEÑA_INVALIDA = "contraseña invalida",
	CONTRASEÑA_IGUAL = "la contraseña debe ser igual a la anterior",
	SELECCIONA = "Selecciona una opcion",
	NINGUNA = "Ninguna",
}
export enum LavelType {
	NOMBRE = "Nombre",
	APELLIDO = "Apellido",
	EMAIL = "Email",
	CONTRASEÑA = "Contraseña",
	RECUPERAR = "Recuperar contraseña",
	REPETIR = "Repetir Contraseña",
	NUEVO = "Nuevo",
	AGREGAR = "Agregar",
	LOGIN = "Login",
	REGISTRARME = "Registrarme",
	FILTRAR = "Filtrar",
	CANCELAR = "Cancelar",
	CONFIRMAR = "Confirmar",
	MANTENER_SESION_INICIADA = "mantener sesion iniciada",
	INICIAR_SESION = "Iniciar Sesion",
	TOKEN = "Token",
	TIPO = "Tipo",
	ULTIMO_VENCIMIENTO = "Ultimo Vencimiento",
	IMPORTANCIA = "Importancia",
	TITULAR = "Titular",
	ULTIMO_MONTO = "Ultimo Monto",
	COMPARTIR = "Compartir",
	NUMERO_DE_CLIENTE = "Numero De Cliente",
	ATENCION_AL_CLIENTE = "Atencion Al Cliente",
	EMAIL_O_USUARIO = "Email O Usuario",
	MES = "Mes",
	AÑO = "Año",
	PERIODO = "Periodo",
	
}
